/*
   This file was generated automatically by Alchitry Labs version 1.2.7.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module game_CU_12 (
    input clk,
    input rst,
    input [15:0] regfiledatab,
    input [15:0] regfiledataa,
    input button,
    output reg [5:0] alufn,
    output reg [2:0] asel,
    output reg [2:0] bsel,
    output reg [1:0] wdsel,
    output reg we,
    output reg [3:0] regfile_write_address,
    output reg [3:0] regfile_read_address_a,
    output reg [3:0] regfile_read_address_b,
    output reg [15:0] state,
    output reg [15:0] debug
  );
  
  
  
  localparam IDLE_game_fsm = 6'd0;
  localparam SETSTART_game_fsm = 6'd1;
  localparam RESET2_game_fsm = 6'd2;
  localparam RESET3_game_fsm = 6'd3;
  localparam RESET4_game_fsm = 6'd4;
  localparam RESET5_game_fsm = 6'd5;
  localparam RESET6_game_fsm = 6'd6;
  localparam RESET7_game_fsm = 6'd7;
  localparam RESET8_game_fsm = 6'd8;
  localparam CHECK2_game_fsm = 6'd9;
  localparam CHECK3_game_fsm = 6'd10;
  localparam CHECK4_game_fsm = 6'd11;
  localparam CHECK5_game_fsm = 6'd12;
  localparam CHECK6_game_fsm = 6'd13;
  localparam CHECK7_game_fsm = 6'd14;
  localparam CHECK8_game_fsm = 6'd15;
  localparam LINE1_game_fsm = 6'd16;
  localparam LINE2_game_fsm = 6'd17;
  localparam LINE3_game_fsm = 6'd18;
  localparam LINE4_game_fsm = 6'd19;
  localparam LINE5_game_fsm = 6'd20;
  localparam LINE6_game_fsm = 6'd21;
  localparam LINE7_game_fsm = 6'd22;
  localparam LINE8_game_fsm = 6'd23;
  localparam SHIFTL1_game_fsm = 6'd24;
  localparam SHIFTL2_game_fsm = 6'd25;
  localparam SHIFTL3_game_fsm = 6'd26;
  localparam SHIFTL4_game_fsm = 6'd27;
  localparam SHIFTL5_game_fsm = 6'd28;
  localparam SHIFTL6_game_fsm = 6'd29;
  localparam SHIFTL7_game_fsm = 6'd30;
  localparam SHIFTL8_game_fsm = 6'd31;
  localparam SHIFTR1_game_fsm = 6'd32;
  localparam SHIFTR2_game_fsm = 6'd33;
  localparam SHIFTR3_game_fsm = 6'd34;
  localparam SHIFTR4_game_fsm = 6'd35;
  localparam SHIFTR5_game_fsm = 6'd36;
  localparam SHIFTR6_game_fsm = 6'd37;
  localparam SHIFTR7_game_fsm = 6'd38;
  localparam SHIFTR8_game_fsm = 6'd39;
  localparam LOSE_game_fsm = 6'd40;
  localparam LEVELUP_game_fsm = 6'd41;
  localparam RESETLINE_game_fsm = 6'd42;
  localparam INCREASELINE_game_fsm = 6'd43;
  localparam INCREASESCORE_game_fsm = 6'd44;
  localparam DETERMINENEXT_game_fsm = 6'd45;
  localparam CHECKLOSE_game_fsm = 6'd46;
  localparam MINUS8_game_fsm = 6'd47;
  
  reg [5:0] M_game_fsm_d, M_game_fsm_q = IDLE_game_fsm;
  reg [15:0] M_state_counter_d, M_state_counter_q = 1'h0;
  reg [15:0] M_statedff_d, M_statedff_q = 1'h0;
  
  always @* begin
    M_game_fsm_d = M_game_fsm_q;
    M_statedff_d = M_statedff_q;
    M_state_counter_d = M_state_counter_q;
    
    alufn = 1'h0;
    asel = 1'h0;
    bsel = 1'h0;
    we = 1'h0;
    wdsel = 1'h0;
    regfile_write_address = 1'h0;
    regfile_read_address_a = 1'h0;
    regfile_read_address_b = 1'h0;
    state = M_statedff_q;
    M_state_counter_d = 1'h0;
    debug = M_state_counter_q;
    if (rst) begin
      M_game_fsm_d = IDLE_game_fsm;
    end else begin
      
      case (M_game_fsm_q)
        IDLE_game_fsm: begin
          regfile_write_address = 4'h9;
          wdsel = 2'h1;
          we = 1'h1;
          M_statedff_d = regfiledataa;
          regfile_read_address_a = 4'hb;
          M_state_counter_d = 1'h0;
          if (button) begin
            M_game_fsm_d = SETSTART_game_fsm;
          end else begin
            M_game_fsm_d = IDLE_game_fsm;
          end
        end
        SETSTART_game_fsm: begin
          regfile_write_address = 4'h9;
          we = 1'h1;
          wdsel = 2'h2;
          M_state_counter_d = 1'h1;
          M_statedff_d = regfiledataa;
          regfile_read_address_a = 4'hb;
          if (button) begin
            M_game_fsm_d = RESET2_game_fsm;
          end else begin
            M_game_fsm_d = SETSTART_game_fsm;
          end
        end
        RESET2_game_fsm: begin
          regfile_write_address = 4'ha;
          wdsel = 1'h1;
          we = 1'h1;
          M_statedff_d = regfiledataa;
          regfile_read_address_a = 10'h3f3;
          M_state_counter_d = 2'h2;
          if (button) begin
            M_game_fsm_d = RESET3_game_fsm;
          end else begin
            M_game_fsm_d = RESET2_game_fsm;
          end
        end
        RESET3_game_fsm: begin
          regfile_write_address = 4'hb;
          wdsel = 1'h1;
          we = 1'h1;
          M_statedff_d = regfiledataa;
          regfile_read_address_a = 10'h3f3;
          M_state_counter_d = 2'h3;
          if (button) begin
            M_game_fsm_d = RESET4_game_fsm;
          end else begin
            M_game_fsm_d = RESET3_game_fsm;
          end
        end
        RESET4_game_fsm: begin
          regfile_write_address = 7'h64;
          wdsel = 1'h1;
          we = 1'h1;
          M_statedff_d = regfiledataa;
          regfile_read_address_a = 10'h3f3;
          M_state_counter_d = 3'h4;
          if (button) begin
            M_game_fsm_d = RESET5_game_fsm;
          end else begin
            M_game_fsm_d = RESET4_game_fsm;
          end
        end
        RESET5_game_fsm: begin
          regfile_write_address = 7'h65;
          wdsel = 1'h1;
          we = 1'h1;
          M_statedff_d = regfiledataa;
          regfile_read_address_a = 10'h3f3;
          M_state_counter_d = 3'h5;
          if (button) begin
            M_game_fsm_d = RESET6_game_fsm;
          end else begin
            M_game_fsm_d = RESET5_game_fsm;
          end
        end
        RESET6_game_fsm: begin
          regfile_write_address = 7'h6e;
          wdsel = 1'h1;
          we = 1'h1;
          M_statedff_d = regfiledataa;
          M_state_counter_d = 3'h6;
          regfile_read_address_a = 10'h3f3;
          if (button) begin
            M_game_fsm_d = RESET7_game_fsm;
          end else begin
            M_game_fsm_d = RESET6_game_fsm;
          end
        end
        RESET7_game_fsm: begin
          regfile_write_address = 7'h6f;
          wdsel = 1'h1;
          we = 1'h1;
          M_statedff_d = regfiledataa;
          M_state_counter_d = 3'h7;
          regfile_read_address_a = 10'h3f3;
          if (button) begin
            M_game_fsm_d = RESET8_game_fsm;
          end else begin
            M_game_fsm_d = RESET7_game_fsm;
          end
        end
        RESET8_game_fsm: begin
          regfile_write_address = 10'h3e8;
          wdsel = 1'h1;
          we = 1'h1;
          M_state_counter_d = 4'h8;
          M_statedff_d = regfiledataa;
          regfile_read_address_a = 10'h3f3;
          if (button) begin
            M_game_fsm_d = INCREASELINE_game_fsm;
          end else begin
            M_game_fsm_d = RESET8_game_fsm;
          end
        end
        INCREASELINE_game_fsm: begin
          regfile_read_address_a = 4'hb;
          regfile_write_address = 4'hb;
          alufn = 6'h00;
          asel = 2'h0;
          bsel = 2'h1;
          we = 1'h1;
          M_state_counter_d = 4'h9;
          M_statedff_d = regfiledataa;
          regfile_read_address_a = 10'h3f3;
          if (button) begin
            M_game_fsm_d = DETERMINENEXT_game_fsm;
          end else begin
            M_game_fsm_d = INCREASELINE_game_fsm;
          end
        end
        DETERMINENEXT_game_fsm: begin
          regfile_read_address_b = 10'h3f3;
          M_statedff_d = regfiledatab;
          M_state_counter_d = 4'ha;
          if (button) begin
            if (regfiledatab == 16'h0001) begin
              M_game_fsm_d = LINE1_game_fsm;
            end else begin
              if (regfiledatab == 16'h0002) begin
                M_game_fsm_d = LINE2_game_fsm;
              end else begin
                if (regfiledatab == 16'h0003) begin
                  M_game_fsm_d = LINE3_game_fsm;
                end else begin
                  if (regfiledatab == 16'h0004) begin
                    M_game_fsm_d = LINE4_game_fsm;
                  end else begin
                    if (regfiledatab == 16'h0005) begin
                      M_game_fsm_d = LINE5_game_fsm;
                    end else begin
                      if (regfiledatab == 16'h0006) begin
                        M_game_fsm_d = LINE6_game_fsm;
                      end else begin
                        if (regfiledatab == 16'h0007) begin
                          M_game_fsm_d = LINE7_game_fsm;
                        end else begin
                          if (regfiledatab == 16'h0008) begin
                            M_game_fsm_d = LINE8_game_fsm;
                          end
                        end
                      end
                    end
                  end
                end
              end
            end
          end else begin
            M_game_fsm_d = DETERMINENEXT_game_fsm;
          end
        end
        LINE1_game_fsm: begin
          alufn = 6'h00;
          we = 1'h1;
          regfile_write_address = 1'h1;
          regfile_read_address_a = 10'h3e9;
          asel = 1'h0;
          M_statedff_d = 8'h0e;
          M_state_counter_d = 4'hb;
          if (button) begin
            M_game_fsm_d = INCREASELINE_game_fsm;
          end else begin
            M_game_fsm_d = SHIFTL1_game_fsm;
          end
        end
        LINE2_game_fsm: begin
          alufn = 6'h00;
          asel = 1'h0;
          we = 1'h1;
          regfile_write_address = 4'ha;
          regfile_read_address_a = 10'h3e9;
          if (button) begin
            M_game_fsm_d = CHECK2_game_fsm;
          end else begin
            M_game_fsm_d = SHIFTL2_game_fsm;
          end
        end
        LINE3_game_fsm: begin
          alufn = 6'h00;
          asel = 1'h0;
          we = 1'h1;
          regfile_write_address = 4'hb;
          regfile_read_address_a = 10'h3e9;
          if (button) begin
            M_game_fsm_d = CHECK3_game_fsm;
          end else begin
            M_game_fsm_d = SHIFTL3_game_fsm;
          end
        end
        LINE4_game_fsm: begin
          alufn = 6'h00;
          asel = 1'h0;
          we = 1'h1;
          regfile_write_address = 7'h64;
          regfile_read_address_a = 10'h3e9;
          if (button) begin
            M_game_fsm_d = CHECK4_game_fsm;
          end else begin
            M_game_fsm_d = SHIFTL4_game_fsm;
          end
        end
        LINE5_game_fsm: begin
          alufn = 6'h00;
          asel = 1'h0;
          we = 1'h1;
          regfile_write_address = 7'h65;
          regfile_read_address_a = 10'h3e9;
          if (button) begin
            M_game_fsm_d = CHECK5_game_fsm;
          end else begin
            M_game_fsm_d = SHIFTL5_game_fsm;
          end
        end
        LINE6_game_fsm: begin
          alufn = 6'h00;
          asel = 1'h0;
          we = 1'h1;
          regfile_write_address = 7'h6e;
          regfile_read_address_a = 10'h3e9;
          if (button) begin
            M_game_fsm_d = CHECK6_game_fsm;
          end else begin
            M_game_fsm_d = SHIFTL6_game_fsm;
          end
        end
        LINE7_game_fsm: begin
          alufn = 6'h00;
          asel = 1'h0;
          we = 1'h1;
          regfile_write_address = 7'h6f;
          regfile_read_address_a = 10'h3e9;
          if (button) begin
            M_game_fsm_d = CHECK7_game_fsm;
          end else begin
            M_game_fsm_d = SHIFTL7_game_fsm;
          end
        end
        LINE8_game_fsm: begin
          alufn = 6'h00;
          asel = 1'h0;
          we = 1'h1;
          regfile_write_address = 10'h3e8;
          regfile_read_address_a = 10'h3e9;
          if (button) begin
            M_game_fsm_d = CHECK8_game_fsm;
          end else begin
            M_game_fsm_d = SHIFTL8_game_fsm;
          end
        end
        LOSE_game_fsm: begin
          wdsel = 1'h1;
          regfile_write_address = 1'h0;
          we = 1'h1;
          if (button) begin
            M_game_fsm_d = IDLE_game_fsm;
          end else begin
            M_game_fsm_d = LOSE_game_fsm;
          end
        end
        CHECK2_game_fsm: begin
          alufn = 6'h08;
          regfile_read_address_a = 4'ha;
          regfile_read_address_b = 1'h1;
          regfile_write_address = 10'h3e9;
          we = 1'h1;
          asel = 1'h0;
          bsel = 1'h0;
          M_game_fsm_d = CHECKLOSE_game_fsm;
        end
        CHECK3_game_fsm: begin
          alufn = 6'h08;
          regfile_read_address_a = 4'hb;
          regfile_read_address_b = 4'ha;
          regfile_write_address = 10'h3e9;
          we = 1'h1;
          asel = 1'h0;
          bsel = 1'h0;
          M_game_fsm_d = CHECKLOSE_game_fsm;
        end
        CHECK4_game_fsm: begin
          alufn = 6'h08;
          regfile_read_address_a = 7'h64;
          regfile_read_address_b = 4'hb;
          regfile_write_address = 10'h3e9;
          we = 1'h1;
          asel = 1'h0;
          bsel = 1'h0;
          M_game_fsm_d = CHECKLOSE_game_fsm;
        end
        CHECK5_game_fsm: begin
          alufn = 6'h08;
          regfile_read_address_a = 7'h65;
          regfile_read_address_b = 7'h64;
          regfile_write_address = 10'h3e9;
          we = 1'h1;
          asel = 1'h0;
          bsel = 1'h0;
          M_game_fsm_d = CHECKLOSE_game_fsm;
        end
        CHECK6_game_fsm: begin
          alufn = 6'h08;
          regfile_read_address_a = 7'h6e;
          regfile_read_address_b = 7'h64;
          regfile_write_address = 10'h3e9;
          we = 1'h1;
          asel = 1'h0;
          bsel = 1'h0;
          M_game_fsm_d = CHECKLOSE_game_fsm;
        end
        CHECK7_game_fsm: begin
          alufn = 6'h08;
          regfile_read_address_a = 7'h6f;
          regfile_read_address_b = 7'h6e;
          regfile_write_address = 10'h3e9;
          we = 1'h1;
          asel = 1'h0;
          bsel = 1'h0;
          M_game_fsm_d = CHECKLOSE_game_fsm;
        end
        CHECK8_game_fsm: begin
          alufn = 6'h08;
          regfile_read_address_a = 10'h3e8;
          regfile_read_address_b = 7'h6f;
          regfile_write_address = 10'h3e9;
          we = 1'h1;
          asel = 1'h0;
          bsel = 1'h0;
          M_game_fsm_d = CHECKLOSE_game_fsm;
        end
        CHECKLOSE_game_fsm: begin
          regfile_read_address_b = 10'h3e9;
          regfile_read_address_a = 10'h3f3;
          if (regfiledatab == 16'h0000) begin
            M_game_fsm_d = LOSE_game_fsm;
          end else begin
            if (regfiledataa == 16'h0008) begin
              M_game_fsm_d = LEVELUP_game_fsm;
            end else begin
              M_game_fsm_d = INCREASELINE_game_fsm;
            end
          end
        end
        SHIFTL1_game_fsm: begin
          regfile_read_address_b = 1'h1;
          if (button) begin
            M_game_fsm_d = INCREASELINE_game_fsm;
          end else begin
            if (regfiledatab == 24'h989680) begin
              M_game_fsm_d = SHIFTR1_game_fsm;
            end else begin
              alufn = 6'h20;
              regfile_read_address_a = 1'h1;
              regfile_write_address = 1'h1;
              bsel = 1'h1;
              we = 1'h1;
              M_game_fsm_d = SHIFTL1_game_fsm;
            end
          end
        end
        SHIFTL2_game_fsm: begin
          regfile_read_address_b = 4'ha;
          if (button) begin
            M_game_fsm_d = CHECK2_game_fsm;
          end else begin
            if (regfiledatab == 24'h989680) begin
              M_game_fsm_d = SHIFTR2_game_fsm;
            end else begin
              alufn = 6'h20;
              regfile_read_address_a = 4'ha;
              regfile_write_address = 4'ha;
              bsel = 1'h1;
              we = 1'h1;
              M_game_fsm_d = SHIFTL2_game_fsm;
            end
          end
        end
        SHIFTL3_game_fsm: begin
          regfile_read_address_b = 4'hb;
          if (button) begin
            M_game_fsm_d = CHECK3_game_fsm;
          end else begin
            if (regfiledatab == 24'h989680) begin
              M_game_fsm_d = SHIFTR3_game_fsm;
            end else begin
              alufn = 6'h20;
              regfile_read_address_a = 4'hb;
              regfile_write_address = 4'hb;
              bsel = 1'h1;
              we = 1'h1;
              M_game_fsm_d = SHIFTL3_game_fsm;
            end
          end
        end
        SHIFTL4_game_fsm: begin
          regfile_read_address_b = 7'h64;
          if (button) begin
            M_game_fsm_d = CHECK4_game_fsm;
          end else begin
            if (regfiledatab == 24'h989680) begin
              M_game_fsm_d = SHIFTR1_game_fsm;
            end else begin
              alufn = 6'h20;
              regfile_read_address_a = 7'h64;
              regfile_write_address = 7'h64;
              bsel = 1'h1;
              we = 1'h1;
              M_game_fsm_d = SHIFTL4_game_fsm;
            end
          end
        end
        SHIFTL5_game_fsm: begin
          regfile_read_address_b = 7'h65;
          if (button) begin
            M_game_fsm_d = CHECK5_game_fsm;
          end else begin
            if (regfiledatab == 24'h989680) begin
              M_game_fsm_d = SHIFTR5_game_fsm;
            end else begin
              alufn = 6'h20;
              regfile_read_address_a = 7'h65;
              regfile_write_address = 7'h65;
              bsel = 1'h1;
              we = 1'h1;
              M_game_fsm_d = SHIFTL5_game_fsm;
            end
          end
        end
        SHIFTL6_game_fsm: begin
          regfile_read_address_b = 7'h6e;
          if (button) begin
            M_game_fsm_d = CHECK6_game_fsm;
          end else begin
            if (regfiledatab == 24'h989680) begin
              M_game_fsm_d = SHIFTR6_game_fsm;
            end else begin
              alufn = 6'h20;
              regfile_read_address_a = 7'h6e;
              regfile_write_address = 7'h6e;
              bsel = 1'h1;
              we = 1'h1;
              M_game_fsm_d = SHIFTL6_game_fsm;
            end
          end
        end
        SHIFTL7_game_fsm: begin
          regfile_read_address_b = 7'h6f;
          if (button) begin
            M_game_fsm_d = CHECK7_game_fsm;
          end else begin
            if (regfiledatab == 24'h989680) begin
              M_game_fsm_d = SHIFTR7_game_fsm;
            end else begin
              alufn = 6'h20;
              regfile_read_address_a = 7'h6f;
              regfile_write_address = 7'h6f;
              bsel = 1'h1;
              we = 1'h1;
              M_game_fsm_d = SHIFTL7_game_fsm;
            end
          end
        end
        SHIFTL8_game_fsm: begin
          regfile_read_address_b = 10'h3e8;
          if (button) begin
            M_game_fsm_d = CHECK8_game_fsm;
          end else begin
            if (regfiledatab == 24'h989680) begin
              M_game_fsm_d = SHIFTR8_game_fsm;
            end else begin
              alufn = 6'h20;
              regfile_read_address_a = 10'h3e8;
              regfile_write_address = 10'h3e8;
              bsel = 1'h1;
              asel = 1'h0;
              we = 1'h1;
              M_game_fsm_d = SHIFTL8_game_fsm;
            end
          end
        end
        SHIFTR1_game_fsm: begin
          regfile_read_address_b = 1'h1;
          if (button) begin
            M_game_fsm_d = INCREASELINE_game_fsm;
          end else begin
            if (regfiledatab == 1'h1) begin
              M_game_fsm_d = SHIFTL1_game_fsm;
            end else begin
              alufn = 6'h21;
              regfile_read_address_a = 1'h1;
              regfile_write_address = 1'h1;
              bsel = 1'h1;
              we = 1'h1;
              M_game_fsm_d = SHIFTR1_game_fsm;
            end
          end
        end
        SHIFTR2_game_fsm: begin
          regfile_read_address_b = 4'ha;
          if (button) begin
            M_game_fsm_d = CHECK2_game_fsm;
          end else begin
            if (regfiledatab == 1'h1) begin
              M_game_fsm_d = SHIFTL2_game_fsm;
            end else begin
              alufn = 6'h21;
              regfile_read_address_a = 4'ha;
              regfile_write_address = 4'ha;
              bsel = 1'h1;
              we = 1'h1;
              M_game_fsm_d = SHIFTR2_game_fsm;
            end
          end
        end
        SHIFTR3_game_fsm: begin
          regfile_read_address_b = 4'hb;
          if (button) begin
            M_game_fsm_d = CHECK3_game_fsm;
          end else begin
            if (regfiledatab == 1'h1) begin
              M_game_fsm_d = SHIFTL3_game_fsm;
            end else begin
              alufn = 6'h21;
              regfile_read_address_a = 4'hb;
              regfile_write_address = 4'hb;
              bsel = 1'h1;
              we = 1'h1;
              M_game_fsm_d = SHIFTR3_game_fsm;
            end
          end
        end
        SHIFTR4_game_fsm: begin
          regfile_read_address_b = 7'h64;
          if (button) begin
            M_game_fsm_d = CHECK4_game_fsm;
          end else begin
            if (regfiledatab == 24'h989680) begin
              M_game_fsm_d = SHIFTL1_game_fsm;
            end else begin
              alufn = 6'h21;
              regfile_read_address_a = 7'h64;
              regfile_write_address = 7'h64;
              bsel = 1'h1;
              we = 1'h1;
              M_game_fsm_d = SHIFTR4_game_fsm;
            end
          end
        end
        SHIFTR5_game_fsm: begin
          regfile_read_address_b = 7'h65;
          if (button) begin
            M_game_fsm_d = CHECK5_game_fsm;
          end else begin
            if (regfiledatab == 1'h1) begin
              M_game_fsm_d = SHIFTL5_game_fsm;
            end else begin
              alufn = 6'h21;
              regfile_read_address_a = 7'h65;
              regfile_write_address = 7'h65;
              bsel = 1'h1;
              we = 1'h1;
              M_game_fsm_d = SHIFTR5_game_fsm;
            end
          end
        end
        SHIFTR6_game_fsm: begin
          regfile_read_address_b = 7'h6e;
          if (button) begin
            M_game_fsm_d = CHECK6_game_fsm;
          end else begin
            if (regfiledatab == 1'h1) begin
              M_game_fsm_d = SHIFTL6_game_fsm;
            end else begin
              alufn = 6'h21;
              regfile_read_address_a = 7'h6e;
              regfile_write_address = 7'h6e;
              bsel = 1'h1;
              we = 1'h1;
              M_game_fsm_d = SHIFTR6_game_fsm;
            end
          end
        end
        SHIFTR7_game_fsm: begin
          regfile_read_address_b = 7'h6f;
          if (button) begin
            M_game_fsm_d = CHECK7_game_fsm;
          end else begin
            if (regfiledatab == 1'h1) begin
              M_game_fsm_d = SHIFTL7_game_fsm;
            end else begin
              alufn = 6'h21;
              regfile_read_address_a = 7'h6f;
              regfile_write_address = 7'h6f;
              bsel = 1'h1;
              we = 1'h1;
              M_game_fsm_d = SHIFTR7_game_fsm;
            end
          end
        end
        SHIFTR8_game_fsm: begin
          regfile_read_address_b = 10'h3e8;
          if (button) begin
            M_game_fsm_d = CHECK8_game_fsm;
          end else begin
            if (regfiledatab == 1'h1) begin
              M_game_fsm_d = SHIFTL8_game_fsm;
            end else begin
              alufn = 6'h21;
              regfile_read_address_a = 10'h3e8;
              regfile_write_address = 10'h3e8;
              bsel = 1'h1;
              asel = 1'h0;
              we = 1'h1;
              M_game_fsm_d = SHIFTR8_game_fsm;
            end
          end
        end
        LEVELUP_game_fsm: begin
          alufn = 6'h00;
          regfile_read_address_a = 10'h3e9;
          regfile_write_address = 1'h1;
          asel = 1'h0;
          bsel = 1'h0;
          we = 1'h1;
          M_game_fsm_d = INCREASESCORE_game_fsm;
        end
        INCREASESCORE_game_fsm: begin
          alufn = 6'h00;
          regfile_read_address_a = 1'h0;
          regfile_write_address = 1'h0;
          asel = 1'h0;
          bsel = 1'h1;
          we = 1'h1;
          M_game_fsm_d = RESETLINE_game_fsm;
        end
        RESETLINE_game_fsm: begin
          regfile_write_address = 10'h3f3;
          wdsel = 4'hb;
          M_game_fsm_d = RESET2_game_fsm;
        end
      endcase
    end
  end
  
  always @(posedge clk) begin
    M_game_fsm_q <= M_game_fsm_d;
    
    if (rst == 1'b1) begin
      M_state_counter_q <= 1'h0;
      M_statedff_q <= 1'h0;
    end else begin
      M_state_counter_q <= M_state_counter_d;
      M_statedff_q <= M_statedff_d;
    end
  end
  
endmodule
